---
# DigitalOcean access token
do_token: "{{ vault_do_token }}"
# Generated ha auth key. Consult README.md for how to generate.
minio_ha_auth_key: "{{ vault_minio_ha_auth_key }}"
minio_floating_ip: "{{ hostvars[groups['storage_fip'][0]]['ip_address'] }}"
primary_name: "{{ hostvars[groups['storage_gateway'][0]].name }}"
primary_address: "{{ hostvars[groups['storage_gateway'][0]].ipv4_address }}"
secondary_name: "{{ hostvars[groups['storage_gateway'][1]].name }}"
secondary_address: "{{ hostvars[groups['storage_gateway'][1]].ipv4_address }}"
