---
- hosts: all
  gather_facts: yes
  become: True

- hosts: load_balancer
  roles:
    - ansible-haproxy
  become: True

- hosts: backend_node
  roles:
    - ansible-backend
  become: True

- hosts: storage_gateway
  roles:
    - blockstore_config
    - gluster_minio
    - minio
    - ha-minio
  become: True

- hosts: galera_lb
  roles:
    - ansible-galera-loadbalancer
  become: True

- hosts: galera_cluster_node
  roles:
    - ansible-galera-cluster
  become: True
