---
- hosts: all
  gather_facts: yes
  become: true

- hosts: load_balancer
  roles:
    - ansible-haproxy
  become: true

- hosts: backend_node
  roles:
    - ansible-backend
  become: true

#- hosts: storage_gateway
#  roles:
#    - blockstore_config
#    - gluster_minio
#    - minio
#    - ha

- hosts: galera_lb
  roles:
    - ansible-galera-loadbalancer
  become: true

- hosts: galera_cluster_node
  roles:
    - ansible-galera-cluster
  become: true