---
- hosts: all
  become: true
  gather_facts: yes

- hosts: load_balancer
  become: true
  roles:
    - ansible-haproxy

- hosts: backend_node
  become: true
  roles:
    - ansible-backend

#- hosts: storage_gateway
#  roles:
#    - blockstore_config
#    - gluster_minio
#    - minio

- hosts: galera_cluster_node
  become: true
  roles:
    - ansible-galera-cluster
