---
# tasks file for /home/fabian/workspace/digitalocean/playground/droplet-to-volume-attach/roles/blockstore_config
- name: set up custom directory for mount
  file:
    path: "{{ mnt_dir }}"
    state: directory

- name: format block device to ext4
  filesystem:
    fstype: ext4
    dev: "{{ device }}"

- name: mount new block storage file system
  mount:
    state: mounted
    fstype: ext4
    name: "{{ mnt_dir }}"
    src: "{{ device }}"
    opts: "discard,defaults"
