---
floating_ip: "{{ hostvars[groups['ha_fip'][0]]['ip_address'] }}"
primary_name: "{{ hostvars[groups['load_balancer'][0]].name }}"
primary_address: "{{ hostvars[groups['load_balancer'][0]].ipv4_address }}"
secondary_name: "{{ hostvars[groups['load_balancer'][1]].name }}"
secondary_address: "{{ hostvars[groups['load_balancer'][1]].ipv4_address }}"
